import torch
from torch import nn
from torch.ao.quantization import QConfig, HistogramObserver, MinMaxObserver
from tqdm import tqdm
import numpy as np
import sys

sys.path.append("..")
from models.ddpm import DDPMSampler

def quantize_cond_encoder(model, tokenizer):
    model.eval()
    torch.backends.quantized.engine = 'qnnpack'
    quantized_model = torch.ao.quantization.quantize_dynamic(model, dtype=torch.qint8)  
    return quantized_model

def quantize_vae(model):
    model.eval()
    
    torch.backends.quantized.engine = 'qnnpack'
    # qconfig = QConfig(activation=HistogramObserver, weight=torch.ao.quantization.default_observer.with_args(dtype=torch.qint8))
    # torch.backends.quantized.engine = 'qnnpack'
    # model.qconfig = qconfig
    # model = torch.ao.quantization.prepare(model)
    
    # ### Calibrate
    # with torch.no_grad():
    #     for _ in tqdm(range(50)):
    #         random_tensor = torch.randn((1, 3, 512, 512), dtype=torch.float32)
    #         model.encode(random_tensor)
    #         random_tensor_2 = torch.randn((1, 4, 64, 64), dtype=torch.float32)
    #         model.decode(random_tensor_2)

    # quantized_model = torch.ao.quantization.convert(model)
    quantized_model = torch.ao.quantization.quantize_dynamic(model, dtype=torch.qint8)  
    return quantized_model

def quantize_unet(model):
    model.eval()
    
    torch.backends.quantized.engine = 'qnnpack'
    # qconfig = QConfig(activation=HistogramObserver, weight=torch.ao.quantization.default_observer.with_args(dtype=torch.qint8))
    # model.qconfig = qconfig
    # torch.backends.quantized.engine = 'qnnpack'
    # model = torch.ao.quantization.prepare(model)

    # ### Calibrate
    # calibrate_unet(model)

    # quantized_model = torch.ao.quantization.convert(model)
    quantized_model = torch.ao.quantization.quantize_dynamic(model, dtype=torch.qint8)  
    return quantized_model


def calibrate_cond_encoder(model, tokenizer):
    uncond_prompt = ''
    prompts = [
    "A cozy mountain cabin at sunrise",
    "A futuristic cityscape with flying cars",
    "A serene beach at sunset with palm trees",
    "A bustling medieval marketplace",
    "A magical forest with glowing mushrooms",
    "A steampunk airship in the sky",
    "A peaceful Japanese garden with cherry blossoms",
    "A lively street scene in Paris",
    "A spooky haunted house on a hill",
    "A vibrant coral reef underwater",
    "An astronaut floating in space with Earth in the background",
    "A fairy-tale castle surrounded by a moat",
    "A tranquil snowy landscape with a lone pine tree",
    "A vintage carnival with a Ferris wheel",
    "A dragon flying over a mountain range",
    "A cozy library with a roaring fireplace",
    "A serene desert landscape with sand dunes",
    "A futuristic robot in a sleek design",
    "A pirate ship sailing on the open sea",
    "A mystical unicorn in an enchanted forest",
    "A serene lake with mountains in the background",
    "A bustling New York City street at night",
    "A tropical island with crystal clear water",
    "A whimsical candy land with giant lollipops",
    "A peaceful countryside with rolling hills",
    "A gothic cathedral with stained glass windows",
    "A serene waterfall in a lush jungle",
    "A futuristic train speeding through a city",
    "A quaint European village with cobblestone streets",
    "A cozy coffee shop with people reading and chatting",
    "A serene ocean view with sailboats in the distance",
    "A vibrant autumn forest with falling leaves",
    "A bustling Tokyo street at night with neon lights",
    "A magical underwater city with mermaids",
    "A peaceful meadow with wildflowers",
    "A futuristic space station orbiting a planet",
    "A cozy cottage in the woods",
    "A vibrant city skyline at dusk",
    "A serene mountain lake with reflections",
    "A lively farmer’s market with fresh produce",
    "A tranquil zen garden with raked sand",
    "A bustling Italian piazza with a fountain",
    "A futuristic flying car in a cityscape",
    "A mystical phoenix rising from the ashes",
    "A serene alpine village with snow-capped peaks",
    "A whimsical treehouse in a giant tree",
    "A bustling Moroccan bazaar with colorful goods",
    "A peaceful river with swans swimming",
    "A futuristic drone delivering a package",
    "A magical fairy garden with tiny houses",
    "A serene beach with a hammock between palm trees",
    "A bustling London street with double-decker buses",
    "A tranquil lavender field at sunrise",
    "A futuristic skyscraper with a rooftop garden",
    "A mystical wizard’s tower in the mountains",
    "A peaceful vineyard with grapevines",
    "A bustling Indian market with spices and fabrics",
    "A serene lake with a wooden dock",
    "A futuristic robot assistant in a home",
    "A whimsical gingerbread house in a snowy forest",
    "A lively Brazilian carnival with dancers",
    "A tranquil hot air balloon floating over a valley",
    "A bustling Hong Kong street with signs and lights",
    "A serene prairie with bison grazing",
    "A futuristic electric car on a highway",
    "A magical snow globe with a winter scene",
    "A peaceful bamboo forest with a small stream",
    "A bustling street food market with vendors",
    "A tranquil mountain meadow with grazing deer",
    "A futuristic underwater research facility",
    "A whimsical toy store with colorful displays",
    "A lively Mardi Gras parade with floats",
    "A serene coastal cliff with crashing waves",
    "A bustling Istanbul market with lanterns",
    "A peaceful orchard with blossoming trees",
    "A futuristic space colony on Mars",
    "A magical woodland creature in a forest",
    "A serene fjord with steep cliffs",
    "A bustling Buenos Aires street with tango dancers",
    "A tranquil sunflower field at sunset",
    "A futuristic hoverboard race in a city",
    "A whimsical enchanted castle in the clouds",
    "A lively African safari with animals",
    "A serene mountain stream with rocks and trees",
    "A bustling Mexican market with colorful crafts",
    "A peaceful garden with a stone path",
    "A futuristic cyberpunk alleyway",
    "A magical dragon’s lair with treasure",
    "A tranquil lake house with a boat dock",
    "A bustling Rio de Janeiro street with samba dancers",
    "A serene tea plantation with rolling hills",
    "A futuristic city with green rooftops",
    "A whimsical carousel with fantasy animals",
    "A lively Oktoberfest celebration with beer tents",
    "A peaceful riverbank with willow trees",
    "A futuristic smart home with AI assistants",
    "A magical ice castle in a winter wonderland",
    "A bustling Moroccan desert caravan",
    "A serene lighthouse on a rocky shore",
    "A futuristic city with flying bicycles",
    "A mystical forest with a hidden waterfall",
    "A peaceful beach with a driftwood bonfire",
    "A bustling Asian night market with street food",
    "A tranquil mountain path with a wooden bridge",
    "A futuristic city with holographic advertisements",
    "A whimsical forest with talking animals",
    "A serene garden with a koi pond",
    "A bustling Brazilian beach with colorful umbrellas",
    "A peaceful meadow with a wooden swing",
    "A futuristic spaceport with starships",
    "A magical library with floating books",
    "A bustling farmers' market with fresh flowers",
    "A serene lakeside with ducks swimming",
    "A futuristic city with monorails and flying cars",
    "A whimsical bakery with giant cupcakes",
    "A lively festival with fireworks",
    "A peaceful village with cobblestone streets",
    "A bustling carnival with acrobats and jugglers",
    "A tranquil forest with a babbling brook",
    "A futuristic city with skyscrapers and green parks",
    "A magical forest with fairy lights",
    "A bustling European market square",
    "A serene mountain valley with a river",
    "A whimsical village with candy-colored houses",
    "A lively parade with floats and balloons",
    "A peaceful beach with seashells and starfish",
    "A bustling city park with people walking dogs",
    "A tranquil forest clearing with a campfire",
    "A futuristic city with glass buildings and gardens",
    "A magical garden with giant flowers",
    "A bustling city street with food trucks",
    "A serene mountain lake with a small boat",
    "A whimsical fairground with colorful rides",
    "A lively beach party with tiki torches",
    "A peaceful village with thatched-roof cottages",
    "A bustling night market with lanterns",
    "A tranquil garden with a waterfall and koi fish",
    "A futuristic city with robots and flying taxis",
    "A magical forest with a hidden castle",
    "A bustling city square with street performers",
    "A serene beach with a lighthouse",
    "A whimsical village with windmills",
    "A lively street festival with music and dancing",
    "A peaceful forest with a wooden cabin",
    "A bustling city with neon signs and skyscrapers",
    "A tranquil meadow with a wooden fence",
    "A futuristic city with transparent buildings",
    "A magical forest with a unicorn",
    "A bustling market with spices and fabrics",
    "A serene beach with a boardwalk",
    "A whimsical forest with giant mushrooms",
    "A lively market with fruit stalls",
    "A peaceful garden with a gazebo",
    "A bustling cityscape with traffic and skyscrapers",
    "A tranquil mountain range with snow-capped peaks",
    "A futuristic city with flying drones",
    "A magical forest with a glowing tree",
    "A bustling street with cafes and shops",
    "A serene beach with a sailboat",
    "A whimsical village with cobblestone streets",
    "A lively market with musicians and dancers",
    "A peaceful forest with a babbling brook",
    "A bustling city with people and cars",
    "A tranquil garden with a stone pathway",
    "A futuristic city with sleek architecture",
    "A magical forest with a hidden cottage",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a hammock",
    "A whimsical town with fairy-tale houses",
    "A lively carnival with clowns and acrobats",
    "A peaceful village with gardens and trees",
    "A bustling city with bright lights and tall buildings",
    "A tranquil forest with a pond",
    "A futuristic city with robots and hovercars",
    "A magical garden with a crystal fountain",
    "A bustling street with vendors and shoppers",
    "A serene beach with a pier",
    "A whimsical village with quaint houses",
    "A lively market with food stalls",
    "A peaceful garden with a bench",
    "A bustling city with tall skyscrapers",
    "A tranquil mountain with a stream",
    "A futuristic city with advanced technology",
    "A magical forest with enchanted creatures",
    "A bustling market with exotic goods",
    "A serene beach with palm trees",
    "A whimsical forest with magical creatures",
    "A lively festival with performers",
    "A peaceful village with cobblestone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying vehicles",
    "A magical forest with hidden treasures",
    "A bustling marketplace with vibrant colors",
    "A serene beach with clear blue water",
    "A whimsical village with quirky houses",
    "A lively parade with colorful floats",
    "A peaceful forest with a clear stream",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with sleek designs",
    "A magical forest with talking animals",
    "A bustling market with street vendors",
    "A serene beach with gentle waves",
    "A whimsical town with charming buildings",
    "A lively street fair with games and food",
    "A peaceful village with gardens and flowers",
    "A bustling city with busy traffic",
    "A tranquil meadow with a wooden bridge",
    "A futuristic city with high-tech gadgets",
    "A magical garden with sparkling lights",
    "A bustling street with lively cafes",
    "A serene beach with colorful seashells",
    "A whimsical forest with fairy houses",
    "A lively festival with music and food",
    "A peaceful garden with a stone bench",
    "A bustling city with people and lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with robotic inhabitants",
    "A magical forest with glowing plants",
    "A bustling market with handmade crafts",
    "A serene beach with soft sand",
    "A whimsical village with unique architecture",
    "A lively parade with dancers and music",
    "A peaceful forest with a flowing river",
    "A bustling city with modern buildings",
    "A tranquil garden with a water feature",
    "A futuristic city with neon lights",
    "A magical forest with mystical creatures",
    "A bustling marketplace with busy shoppers",
    "A serene beach with a sunset view",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with stone houses",
    "A bustling street with neon signs",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with a hidden waterfall",
    "A bustling market with local vendors",
    "A serene beach with a tropical vibe",
    "A whimsical forest with magical elements",
    "A lively parade with festive floats",
    "A peaceful village with flower gardens",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a small pond",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling street with bustling shops",
    "A serene beach with clear waters",
    "A whimsical forest with giant flowers",
    "A lively festival with carnival rides",
    "A peaceful village with cobblestone streets",
    "A bustling city with skyscrapers",
    "A tranquil mountain with a stream",
    "A futuristic city with advanced architecture",
    "A magical forest with mystical creatures",
    "A bustling market with colorful tents",
    "A serene beach with palm trees",
    "A whimsical town with colorful houses",
    "A lively parade with music and dance",
    "A peaceful forest with a babbling brook",
    "A bustling city with neon lights",
    "A tranquil meadow with wildflowers",
    "A futuristic city with sleek buildings",
    "A magical forest with glowing plants",
    "A bustling market with exotic foods",
    "A serene beach with a relaxing atmosphere",
    "A whimsical village with unique homes",
    "A lively festival with food and games",
    "A peaceful garden with blooming flowers",
    "A bustling street with busy shops",
    "A tranquil mountain with a cabin",
    "A futuristic city with robotic citizens",
    "A magical forest with enchanted trees",
    "A bustling marketplace with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with floats and music",
    "A peaceful forest with a clear stream",
    "A bustling city with modern architecture",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden secrets",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest with magical creatures",
    "A lively parade with festive decorations",
    "A peaceful village with stone houses",
    "A bustling city with crowded sidewalks",
    "A tranquil garden with a koi pond",
    "A futuristic city with flying vehicles",
    "A magical garden with sparkling lights",
    "A bustling street with cafes and shops",
    "A serene beach with clear blue waters",
    "A whimsical forest with giant mushrooms",
    "A lively festival with music and dance",
    "A peaceful village with cobblestone streets",
    "A bustling city with tall buildings",
    "A tranquil mountain with a stream",
    "A futuristic city with high-tech designs",
    "A magical forest with enchanted creatures",
    "A bustling market with handmade crafts",
    "A serene beach with gentle waves",
    "A whimsical village with unique architecture",
    "A lively parade with music and floats",
    "A peaceful forest with a flowing river",
    "A bustling city with neon signs",
    "A tranquil garden with a stone path",
    "A futuristic city with sleek designs",
    "A magical forest with mystical elements",
    "A bustling marketplace with busy shoppers",
    "A serene beach with soft sand",
    "A whimsical town with vibrant colors",
    "A lively festival with colorful decorations",
    "A peaceful village with flower gardens",
    "A bustling street with busy shops",
    "A tranquil meadow with wildflowers",
    "A futuristic city with flying cars",
    "A magical garden with hidden paths",
    "A bustling market with local goods",
    "A serene beach with a relaxing vibe",
    "A whimsical forest with fairy houses",
    "A lively festival with food and music",
    "A peaceful garden with a stone bench",
    "A bustling city with neon lights",
    "A tranquil mountain with a cabin",
    "A futuristic city with advanced architecture",
    "A magical forest with glowing trees",
    "A bustling marketplace with colorful stalls",
    "A serene beach with a tropical atmosphere",
    "A whimsical village with colorful homes",
    "A lively parade with festive floats",
    "A peaceful forest with a babbling brook",
    "A bustling city with crowded streets",
    "A tranquil garden with blooming flowers",
    "A futuristic city with high-tech buildings",
    "A magical forest with enchanted plants",
    "A bustling market with exotic foods",
    "A serene beach with clear water",
    "A whimsical town with unique houses",
    "A lively festival with carnival rides",
    "A peaceful village with stone pathways",
    "A bustling street with busy shops",
    "A tranquil meadow with wild animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden creatures",
    "A bustling market with handmade goods",
    "A serene beach with soft waves",
    "A whimsical village with charming cottages",
    "A lively parade with music and floats",
    "A peaceful forest with a clear stream",
    "A bustling city with tall skyscrapers",
    "A tranquil garden with a water fountain",
    "A futuristic city with neon signs",
    "A magical forest with mystical creatures",
    "A bustling market with vibrant colors",
    "A serene beach with a sunset view",
    "A whimsical town with colorful buildings",
    "A lively festival with performers",
    "A peaceful village with flower gardens",
    "A bustling street with neon lights",
    "A tranquil meadow with grazing animals",
    "A futuristic city with advanced technology",
    "A magical forest with hidden waterfalls",
    "A bustling market with local vendors",
    "A serene beach with tropical vibes",
    "A whimsical forest"]
    with torch.no_grad():
        for prompt in tqdm(prompts):
            cond_tokens = torch.tensor(tokenizer.batch_encode_plus([prompt], padding='max_length', max_length=77).input_ids, dtype=torch.long, device='cpu')
            uncond_tokens = torch.tensor(tokenizer.batch_encode_plus([uncond_prompt], padding='max_length', max_length=77).input_ids, dtype=torch.long, device='cpu')
            context = torch.cat([cond_tokens, uncond_tokens], dim=0)
            res = model(context)


def calibrate_unet(model):
    latent_shape = (1, 4, 64, 64)
    random_tensor = torch.randn(latent_shape, dtype=torch.float32)
    context = torch.randn((2, 77, 768), dtype=torch.float32)
    latent_features = random_tensor
    
    generator = torch.Generator(device='cpu')
    generator.seed()
    sampler = DDPMSampler(generator)
    sampler._set_inference_steps(1000)
    cfg_scale = 8
    with torch.no_grad():
        for i, timestep in enumerate(tqdm(sampler.timesteps)):
            model_input = latent_features.repeat(2, 1, 1, 1)
            pred_noise = model(model_input, timestep, context)
            
            cond_output, uncond_output = pred_noise.chunk(2)
            pred_noise = cfg_scale * (cond_output - uncond_output) + uncond_output
            latent_features = sampler.reverse_process(latent_features, timestep, pred_noise)
    